use anyhow::{bail, Context, Result};
use frp_shared::api_types::AgentDesiredProxy;
use frp_shared::config::AgentConfig;
use frp_shared::models::Gateway;
use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use tracing::{info, warn};

pub struct FrpcManager {
    config_dir: PathBuf,
    main_config_path: PathBuf,
    binary_path: PathBuf,
    admin_addr: String,
    admin_user: String,
    admin_pass: String,
    client: reqwest::Client,
}

impl FrpcManager {
    pub fn new(config: &AgentConfig) -> Self {
        Self {
            config_dir: PathBuf::from(&config.frpc_config_dir),
            main_config_path: PathBuf::from(&config.frpc_main_config),
            binary_path: PathBuf::from(&config.frpc_binary_path),
            admin_addr: config.frpc_admin_addr.clone(),
            admin_user: config.frpc_admin_user.clone(),
            admin_pass: config.resolved_admin_password(),
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(5))
                .build()
                .unwrap_or_default(),
        }
    }

    /// Ensure directory structure exists.
    pub fn init_directories(&self) -> Result<()> {
        if !self.config_dir.exists() {
            fs::create_dir_all(&self.config_dir)
                .context(format!("Failed to create config dir: {:?}", self.config_dir))?;
        }
        if let Some(parent) = self.main_config_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
        }
        Ok(())
    }

    /// Render and write the base `frpc.toml` main configuration file.
    pub fn write_main_config(&self, gateway: &Gateway) -> Result<()> {
        let (admin_host, admin_port) = match self.admin_addr.split_once(':') {
            Some((h, p)) => (h, p.parse::<u16>().unwrap_or(7400)),
            None => ("127.0.0.1", 7400),
        };

        let content = format!(
            r#"# FRP Client Main Configuration
# Generated by frp-agent — DO NOT EDIT DIRECTLY

serverAddr = "{server_addr}"
serverPort = {server_port}
auth.method = "token"
auth.token = "{token}"
transport.tls.enable = true

webServer.addr = "{admin_host}"
webServer.port = {admin_port}
webServer.user = "{admin_user}"
webServer.password = "{admin_pass}"

includes = ["{conf_d_glob}"]
"#,
            server_addr = gateway.public_ip,
            server_port = gateway.control_port,
            token = gateway.token,
            admin_host = admin_host,
            admin_port = admin_port,
            admin_user = self.admin_user,
            admin_pass = self.admin_pass,
            conf_d_glob = self.config_dir.join("*.toml").display().to_string().replace('\\', "/")
        );

        fs::write(&self.main_config_path, content)
            .context(format!("Failed to write main config to {:?}", self.main_config_path))?;

        info!(path = %self.main_config_path.display(), "Wrote FRP client main config");
        Ok(())
    }

    /// Synchronize the `conf.d/` directory with desired proxies and trigger dynamic hot-reload.
    /// Returns true if any files were changed.
    pub async fn sync_proxies(&self, desired_proxies: &[AgentDesiredProxy]) -> Result<bool> {
        self.init_directories()?;

        let mut desired_file_names = HashSet::new();
        let mut changes_made = false;

        for proxy in desired_proxies {
            let filename = format!("{}.toml", proxy.proxy_name);
            let filepath = self.config_dir.join(&filename);
            desired_file_names.insert(filename);

            let new_content = self.render_proxy_toml(proxy);

            let should_write = if filepath.exists() {
                match fs::read_to_string(&filepath) {
                    Ok(existing) => existing != new_content,
                    Err(_) => true,
                }
            } else {
                true
            };

            if should_write {
                fs::write(&filepath, &new_content)
                    .context(format!("Failed to write proxy config: {:?}", filepath))?;
                info!(proxy = %proxy.proxy_name, path = %filepath.display(), "Created/Updated FRP proxy config");
                changes_made = true;
            }
        }

        // Clean up obsolete proxy files
        if let Ok(entries) = fs::read_dir(&self.config_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some("toml") {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        if !desired_file_names.contains(name) {
                            if let Err(e) = fs::remove_file(&path) {
                                warn!(path = %path.display(), error = %e, "Failed to remove obsolete proxy config");
                            } else {
                                info!(path = %path.display(), "Removed obsolete FRP proxy config");
                                changes_made = true;
                            }
                        }
                    }
                }
            }
        }

        if changes_made {
            info!("Changes detected in proxy configurations. Triggering hot-reload...");
            self.reload().await?;
        }

        Ok(changes_made)
    }

    /// Render individual proxy TOML block.
    fn render_proxy_toml(&self, proxy: &AgentDesiredProxy) -> String {
        let mut out = String::new();
        let pp_line = match &proxy.proxy_protocol_version {
            Some(v) if v == "v1" || v == "v2" => format!("transport.proxyProtocolVersion = \"{}\"\n", v),
            _ => String::new(),
        };

        if proxy.protocol.is_tcp() {
            let tcp_name = format!("{}_tcp", proxy.proxy_name);
            out.push_str(&format!(
                r#"[[proxies]]
name = "{name}"
type = "tcp"
localIP = "{local_ip}"
localPort = {local_port}
remotePort = {remote_port}
{pp_line}
"#,
                name = tcp_name,
                local_ip = proxy.local_ip,
                local_port = proxy.local_port,
                remote_port = proxy.remote_port,
                pp_line = pp_line
            ));
        }

        if proxy.protocol.is_udp() {
            let udp_name = format!("{}_udp", proxy.proxy_name);
            out.push_str(&format!(
                r#"[[proxies]]
name = "{name}"
type = "udp"
localIP = "{local_ip}"
localPort = {local_port}
remotePort = {remote_port}
{pp_line}
"#,
                name = udp_name,
                local_ip = proxy.local_ip,
                local_port = proxy.local_port,
                remote_port = proxy.remote_port,
                pp_line = pp_line
            ));
        }

        out
    }

    /// Hot-reload frpc via its HTTP admin API or fallback command.
    pub async fn reload(&self) -> Result<()> {
        let url = format!("http://{}/api/reload", self.admin_addr);

        let mut req = self.client.get(&url);
        if !self.admin_user.is_empty() {
            req = req.basic_auth(&self.admin_user, Some(&self.admin_pass));
        }

        match req.send().await {
            Ok(resp) if resp.status().is_success() => {
                info!("FRP client hot-reloaded successfully via Admin API (zero downtime)");
                return Ok(());
            }
            Ok(resp) => {
                warn!(status = %resp.status(), "FRP admin API reload returned non-200 status, attempting CLI fallback");
            }
            Err(e) => {
                warn!(error = %e, "Could not reach FRP admin API at {}, attempting CLI fallback", url);
            }
        }

        // CLI fallback: frpc reload -c /opt/frp/frpc.toml
        if self.binary_path.exists() {
            let status = tokio::process::Command::new(&self.binary_path)
                .args(["reload", "-c", &self.main_config_path.display().to_string()])
                .status()
                .await
                .context("Failed to run frpc reload command")?;

            if status.success() {
                info!("FRP client hot-reloaded successfully via frpc reload command");
                return Ok(());
            }
        }

        bail!("Failed to hot-reload FRP client via both admin API and CLI");
    }

    /// Check if frpc admin API is reachable.
    pub async fn is_alive(&self) -> bool {
        let url = format!("http://{}/api/status", self.admin_addr);
        let mut req = self.client.get(&url);
        if !self.admin_user.is_empty() {
            req = req.basic_auth(&self.admin_user, Some(&self.admin_pass));
        }

        matches!(req.send().await, Ok(resp) if resp.status().is_success())
    }
}
