use anyhow::{Context, Result};
use frp_shared::config::GatewayConfig;
use std::fs;
use std::path::Path;
use tracing::info;

pub struct FrpsConfigGenerator;

impl FrpsConfigGenerator {
    /// Render `frps.toml` configuration string.
    pub fn render_toml(config: &GatewayConfig) -> String {
        let (dash_host, dash_port) = (
            "127.0.0.1",
            config.dashboard_port.unwrap_or(7500),
        );

        let token = frp_shared::config::resolve_secret(&config.token);

        let start_port = config.tcp_port_range.start.min(config.udp_port_range.start);
        let end_port = config.tcp_port_range.end.max(config.udp_port_range.end);

        format!(
            r#"# FRP Server Main Configuration
# Generated by frp-gateway — DO NOT EDIT DIRECTLY

bindAddr = "0.0.0.0"
bindPort = {bind_port}
auth.method = "token"
auth.token = "{token}"

# Restrict proxy port allocation to defined port ranges
allowPorts = [
  {{ start = {start_port}, end = {end_port} }}
]

# Admin Dashboard
webServer.addr = "{dash_host}"
webServer.port = {dash_port}
webServer.user = "admin"
webServer.password = "{token}"
"#,
            bind_port = config.control_port,
            token = token,
            start_port = start_port,
            end_port = end_port,
            dash_host = dash_host,
            dash_port = dash_port,
        )
    }

    /// Write `frps.toml` to specified destination path.
    pub fn write_config(config: &GatewayConfig, target_path: impl AsRef<Path>) -> Result<()> {
        let target_path = target_path.as_ref();
        if let Some(parent) = target_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
        }

        let content = Self::render_toml(config);
        fs::write(target_path, content)
            .context(format!("Failed to write frps configuration to {:?}", target_path))?;

        info!(path = %target_path.display(), "Successfully written frps.toml");
        Ok(())
    }
}
